/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protodefs/message.proto */

#ifndef PROTOBUF_C_protodefs_2fmessage_2eproto__INCLUDED
#define PROTOBUF_C_protodefs_2fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct SampleData SampleData;


/* --- enums --- */


/* --- messages --- */

struct  SampleData
{
  ProtobufCMessage base;
  char *greeting;
};
#define SAMPLE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sample_data__descriptor) \
    , (char *)protobuf_c_empty_string }


/* SampleData methods */
void   sample_data__init
                     (SampleData         *message);
size_t sample_data__get_packed_size
                     (const SampleData   *message);
size_t sample_data__pack
                     (const SampleData   *message,
                      uint8_t             *out);
size_t sample_data__pack_to_buffer
                     (const SampleData   *message,
                      ProtobufCBuffer     *buffer);
SampleData *
       sample_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sample_data__free_unpacked
                     (SampleData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SampleData_Closure)
                 (const SampleData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sample_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protodefs_2fmessage_2eproto__INCLUDED */
