/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protodefs/message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protodefs/message.pb-c.h"
void   sample_data__init
                     (SampleData         *message)
{
  static const SampleData init_value = SAMPLE_DATA__INIT;
  *message = init_value;
}
size_t sample_data__get_packed_size
                     (const SampleData *message)
{
  assert(message->base.descriptor == &sample_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sample_data__pack
                     (const SampleData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sample_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sample_data__pack_to_buffer
                     (const SampleData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sample_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SampleData *
       sample_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SampleData *)
     protobuf_c_message_unpack (&sample_data__descriptor,
                                allocator, len, data);
}
void   sample_data__free_unpacked
                     (SampleData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sample_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sample_data__field_descriptors[1] =
{
  {
    "greeting",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SampleData, greeting),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sample_data__field_indices_by_name[] = {
  0,   /* field[0] = greeting */
};
static const ProtobufCIntRange sample_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sample_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SampleData",
  "SampleData",
  "SampleData",
  "",
  sizeof(SampleData),
  1,
  sample_data__field_descriptors,
  sample_data__field_indices_by_name,
  1,  sample_data__number_ranges,
  (ProtobufCMessageInit) sample_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
